name: Build Release Files

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: '1.65.0'

      - name: build
        run: |
          go build -C generator -o ../deploy/generator

      - name: generate
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          sudo apt install -y zsh
          lua ./table/gen_freq.lua ./table/freq_simp.txt ./table/freq_trad.txt 9:1 > ./deploy/hao/freq.txt
          zsh deploy/deploy_hao.sh  && zsh assets/simpcode/gen_hao_simp.sh &&  zsh deploy/deploy_hao.sh
          cd schemas && tar -cf - "./hao" | zstd -9 -T0 --long=31 -c > "releases/hao-${{ github.ref_name }}.tar.zst" || return 1
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: schemas/releases/hao-${{ github.ref_name }}.tar.zst
          make_latest: 'true'