name: Deploy to GitHub Pages

permissions:
  contents: write

on: push

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: '1.65.0'

      - name: build
        run: |
          go build -C generator -o ../deploy/generator

      - name: generate
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          sudo apt install -y zsh
          zsh deploy/deploy_hao.sh
          zsh assets/simpcode/gen_hao_simp.sh
